export const branches = [
  { id: 1, name: 'Nilüfer Hastanesi' },
  { id: 2, name: 'Yıldırım Hastanesi' },
]

export const services = {
  'Nilüfer Hastanesi': [
    { id: 1, name: 'Acil Servis', to: '/acil-servis' },
    { id: 2, name: 'Ağız ve Diş Sağlığı', to: '/agiz-ve-dis-sagligi' },
    { id: 3, name: 'Anesteziyoloji ve Reanimasyon', to: '/anesteziyoloji-ve-reanimasyon' },
    { id: 4, name: 'Beyin ve Sinir Cerrahisi (Nöroşirürji)', to: '/beyin-ve-sinir-cerrahisi' },
    { id: 5, name: 'Beslenme ve Diyetetik', to: '/beslenme-ve-diyetetik' },
    { id: 6, name: 'Çocuk Cerrahisi', to: '/cocuk-cerrahisi' },
    { id: 7, name: 'Çocuk Sağlığı ve Hastalıkları', to: '/cocuk-sagligi-ve-hastaliklari' },
    { id: 8, name: 'Çocuk ve Ergen Psikiyatrisi', to: '/cocuk-ve-ergen-psikiyatrisi' },
    { id: 9, name: 'Dahiliye (İç Hastalıkları)', to: '/dahiliye' },
    { id: 10, name: 'Dermatoloji (Cildiye)', to: '/dermatoloji' },
    { id: 11, name: 'Enfeksiyon Hastalıkları', to: '/enfeksiyon-hastaliklari' },
    { id: 12, name: 'Fizik Tedavi ve Rehabilitasyon', to: '/fizik-tedavi-ve-rehabilitasyon' },
    { id: 13, name: 'Geleneksel ve Tamamlayıcı Tıp (GETAT)', to: '/getat' },
    { id: 14, name: 'Genel Cerrahi', to: '/genel-cerrahi' },
    { id: 15, name: 'Göğüs Hastalıkları', to: '/gogus-hastaliklari' },
    { id: 16, name: 'Göğüs Cerrahisi', to: '/gogus-cerrahisi' },
    { id: 17, name: 'Göz Hastalıkları', to: '/goz-hastaliklari' },
    { id: 18, name: 'Kadın Hastalıkları ve Doğum', to: '/kadin-hastaliklari-ve-dogum' },
    { id: 19, name: 'Kalp ve Damar Cerrahisi', to: '/kalp-ve-damar-cerrahisi' },
    { id: 20, name: 'Kardiyoloji', to: '/kardiyoloji' },
    { id: 21, name: 'Klinik Psikoloji', to: '/klinik-psikoloji' },
    { id: 22, name: 'Kulak Burun Boğaz Hastalıkları', to: '/kulak-burun-bogaz' },
    { id: 23, name: 'Nöroloji (Beyin ve Sinir Hastalıkları)', to: '/noroloji' },
    { id: 24, name: 'Ortopedi ve Travmatoloji', to: '/ortopedi-ve-travmatoloji' },
    { id: 25, name: 'Psikiyatri', to: '/psikiyatri' },
    { id: 26, name: 'Plastik ve Rekonstruktif Cerrahi', to: '/plastik-ve-rekonstruktif-cerrahi' },
    { id: 27, name: 'Radyoloji', to: '/radyoloji' },
    { id: 28, name: 'Saç Ekimi Merkezi', to: '/sac-ekimi-merkezi' },
    { id: 29, name: 'Tıbbi Onkoloji', to: '/tibbi-onkoloji' },
    { id: 30, name: 'Üroloji', to: '/uroloji' },
  ],
  'Yıldırım Hastanesi': [
    { id: 31, name: 'Anesteziyoloji ve Reanimasyon', to: '/anesteziyoloji-ve-reanimasyon' },
    { id: 32, name: 'Beslenme ve Diyetetik', to: '/beslenme-ve-diyetetik' },
    { id: 33, name: 'Çocuk Sağlığı ve Hastalıkları', to: '/cocuk-sagligi-ve-hastaliklari' },
    { id: 34, name: 'Dahiliye (İç Hastalıkları)', to: '/dahiliye' },
    { id: 35, name: 'Fizik Tedavi ve Rehabilitasyon', to: '/fizik-tedavi-ve-rehabilitasyon' },
    { id: 36, name: 'Göğüs Hastalıkları', to: '/gogus-hastaliklari' },
    { id: 37, name: 'Kadın Hastalıkları ve Doğum', to: '/kadin-hastaliklari-ve-dogum' },
    { id: 38, name: 'Kulak Burun Boğaz Hastalıkları', to: '/kulak-burun-bogaz' },
    { id: 39, name: 'Kardiyoloji', to: '/kardiyoloji' },
    { id: 40, name: 'Nöroloji (Beyin ve Sinir Hastalıkları)', to: '/noroloji' },
    { id: 41, name: 'Ortopedi ve Travmatoloji', to: '/ortopedi-ve-travmatoloji' },
    { id: 42, name: 'Radyoloji', to: '/radyoloji' },
    { id: 43, name: 'Üroloji', to: '/uroloji' },
  ],
}
