export const news = [
  {
    id: 'amerikalı-ünlü-ortopedistten-medicabil-ziyareti',
    title: 'Amerikalı Ünlü Ortopedistten Medicabil Ziyareti',
    content: `Medicabil Sağlık Grubu Yönetim Kurulu Başkanı Prof. Dr. Ömer Faruk Bilgen, Amerika’dan hocası Ortopedist Dr. Chitranjan Singh Ranawat’ın oğlu Amerikalı ünlü Ortopedist Dr. Amar S. Ranawat’ı ve beraberindeki heyeti ağırladı.`,
    img: '/news/news_1.jpg',
    date: '15 Mart 2024',
  },
  {
    id: 'medicabilden-8-mart-dünya-kadınlar-gününde-anlamlı-kutlama',
    title: `Medicabil'den 8 Mart Dünya Kadınlar Günü'nde Anlamlı Kutlama`,
    content: `Medicabil Nilüfer Hastanesi’nde gerçekleşen programın açılışında konuşan Medicabil Sağlık Grubu Yönetim Kurulu Başkanı Prof. Dr. Ömer Faruk Bilgin, anlamlı bir günde kadın çalışanlarıyla bir araya gelmenin mutluluğunu yaşadıklarını söyleyerek tüm kadınların 8 Mart Dünya Kadınlar Günü’nü kutladı.`,
    img: '/news/news_2.jpg',
    date: '11 Mart 2024',
  },
  {
    id: 'medicabilden-8-mart-dünya-kadınlar-gününde-anlamlı-kutlama-2',
    title: "Medicabil'den 8 Mart Dünya Kadınlar Günü'nde Anlamlı Kutlama",
    content: `Paralimpik Oyunlarının tecrübeli ismi, 10m. Havalı tabanca (P2) ve 50m. Serbest Tabanca (P4) dallarında yarışan ve pek çok müsabakaya katılarak birinciliği elde eden milli sporcumuz Aysel Özgan Medicabil Hastanesi’nin kadın çalışanlarıyla deneyimlerini paylaştı.`,
    img: '/news/news_3.jpg',
    date: '1 Mart 2024',
  },
  {
    id: 'iraklı-doktorlarla-ileri-artroplasti-semineri',
    title: 'Iraklı Doktorlarla İleri Artroplasti Semineri',
    content: `Irak’tan Bursa’ya gelen 11 ortopedi doktoru Özel Medicabil Nilüfer Hastanesi’nde 2 gün devam eden İleri Artroplasti Seminerine katıldılar.`,
    img: '/news/news_4.jpg',
    date: '21 Şubat 2024',
  },
  {
    id: 'medicabil-14-yasında',
    title: 'Medicabil 14 Yaşında',
    content: `Medicabil Nilüfer Hastanesi’nde gerçekleşen 14. Yıl kutlamasına Medicabil Sağlık Grubu Yönetim Kurulu Başkanı Prof. Dr. Ömer Faruk Bilgen ile doktorları ve tüm hastane çalışanları katıldı.`,
    img: '/news/news_5.jpg',
    date: '17 Ocak 2024',
  },
  {
    id: 'ramazanda-sağlıklı-beslenme',
    title: 'Ramazanda Sağlıklı Beslenme',
    content: `Ramazan ayında öğün sayısının azalması ve yaklaşık 13 saati bulan açlık süresiyle birlikte günlük alınan enerjinin düşmesi ve sıvı tüketiminin de azalmasına bağlı olarak metabolizma hızı yavaşlamaktadır.`,
    img: '/news/news_6.jpg',
    date: '20 Aralık 2023',
  },
  {
    id: 'yeni-doktorlar-ekibimize-katıldı',
    title: 'Yeni Doktorlar Ekibimize Katıldı',
    content: `Medicabil Sağlık Grubu ailesine yeni katılan doktorlarımızla birlikte daha güçlü bir ekip olarak hizmet vermeye devam ediyoruz.`,
    img: '/news/news_1.jpg',
    date: '10 Nisan 2024',
  },
  {
    id: 'kanser-farkındalık-semineri',
    title: 'Kanser Farkındalık Semineri',
    content: `Kanserle mücadelede erken teşhisin önemine dikkat çekmek için düzenlediğimiz farkındalık seminerine yoğun katılım sağlandı.`,
    img: '/news/news_2.jpg',
    date: '5 Nisan 2024',
  },
  {
    id: 'sporcu-sagligi-ve-beslenme',
    title: 'Sporcu Sağlığı ve Beslenme',
    content: `Sporcular için sağlıklı beslenme ve performans artırıcı öneriler konulu seminerimiz büyük ilgi gördü.`,
    img: '/news/news_3.jpg',
    date: '25 Mart 2024',
  },
  {
    id: 'medicabilde-yeni-teknolojiler',
    title: 'Medicabil’de Yeni Teknolojiler',
    content: `Hastanemize kazandırılan yeni teknolojik cihazlarla tanı ve tedavi süreçlerimizi daha da geliştirdik.`,
    img: '/news/news_4.jpg',
    date: '18 Mart 2024',
  },
  {
    id: 'diyabet-ve-beslenme',
    title: 'Diyabet ve Beslenme',
    content: `Diyabet hastalarına yönelik düzenlediğimiz sağlıklı beslenme semineri büyük ilgi gördü.`,
    img: '/news/news_5.jpg',
    date: '12 Mart 2024',
  },
  {
    id: 'organ-bagisi-semineri',
    title: 'Organ Bağışı Semineri',
    content: `Organ bağışının önemi ve süreçleri hakkında düzenlediğimiz seminerde katılımcılar bilgilendirildi.`,
    img: '/news/news_6.jpg',
    date: '8 Mart 2024',
  },
  {
    id: 'medicabilde-anneler-gunu-kutlamasi',
    title: 'Medicabil’de Anneler Günü Kutlaması',
    content: `Anneler Günü’nde hastanemizde düzenlenen etkinlikte annelerimize özel sürprizler hazırladık.`,
    img: '/news/news_1.jpg',
    date: '14 Mayıs 2024',
  },
  {
    id: 'cocuklarda-asi-takvimi',
    title: 'Çocuklarda Aşı Takvimi',
    content: `Çocukların sağlıklı gelişimi için aşı takviminin önemi hakkında bilgilendirme yaptık.`,
    img: '/news/news_2.jpg',
    date: '30 Nisan 2024',
  },
  {
    id: 'medicabilde-ramazan-yardimlari',
    title: 'Medicabil’de Ramazan Yardımları',
    content: `Ramazan ayında ihtiyaç sahiplerine yönelik yardım kampanyamız büyük destek gördü.`,
    img: '/news/news_3.jpg',
    date: '20 Nisan 2024',
  },
  {
    id: 'yeni-dogum-unitesi-acilisi',
    title: 'Yeni Doğum Ünitesi Açılışı',
    content: `Hastanemizde yeni doğum ünitesinin açılışı gerçekleştirildi ve hizmete sunuldu.`,
    img: '/news/news_4.jpg',
    date: '15 Nisan 2024',
  },
  {
    id: 'medicabilde-23-nisan-etkinlikleri',
    title: 'Medicabil’de 23 Nisan Etkinlikleri',
    content: `23 Nisan Ulusal Egemenlik ve Çocuk Bayramı’nda çocuklar için özel etkinlikler düzenledik.`,
    img: '/news/news_5.jpg',
    date: '23 Nisan 2024',
  },
  {
    id: 'saglikli-yasam-yuruyusu',
    title: 'Sağlıklı Yaşam Yürüyüşü',
    content: `Sağlıklı yaşam bilincini artırmak için düzenlediğimiz yürüyüş etkinliğine yoğun katılım sağlandı.`,
    img: '/news/news_6.jpg',
    date: '28 Nisan 2024',
  },
  {
    id: 'medicabilde-yeni-ameliyathane',
    title: 'Medicabil’de Yeni Ameliyathane',
    content: `Hastanemizde yeni ameliyathane birimimiz hizmete açıldı.`,
    img: '/news/news_1.jpg',
    date: '5 Mayıs 2024',
  },
  {
    id: 'medicabilde-ramazan-bayrami-kutlamasi',
    title: 'Medicabil’de Ramazan Bayramı Kutlaması',
    content: `Ramazan Bayramı’nda hastanemizde düzenlenen etkinliklerle bayram coşkusunu yaşadık.`,
    img: '/news/news_2.jpg',
    date: '10 Mayıs 2024',
  },
  {
    id: 'medicabilde-yeni-hizmetler',
    title: 'Medicabil’de Yeni Hizmetler',
    content: `Hastanemizde başlattığımız yeni hizmetlerle sağlık alanında daha geniş bir yelpazede hizmet sunuyoruz.`,
    img: '/news/news_3.jpg',
    date: '15 Mayıs 2024',
  },
]
